### ISSUE TITLE
Switch Order of Fields on Animal Form During Hotline Workflow

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#101]
In the Hotline Workflow, we need to change up the way the fields are ordered a bit.  Basically we just need to move the First Row (Animal Name, Sex) down below Primary Color/Secondary Color/Description Field.  This allows the first information to be engaged with to be the most important during Hotline work.

**Comment by trevorskaggs** [comment]
Let's also Hide the `Image Files` section during Hotline!

**Comment by cdvieu** [comment]
This work was completed in another issue.
