### ISSUE TITLE
Expose "Animal Details" Button on the DA Resolution page.

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#140]
![image](https://user-images.githubusercontent.com/1276123/101117941-f5cdaf00-359c-11eb-8e51-91e719645041.png)
Need to add little Notebook icon to each animal on the DA Resolution Page, should open Animal Details page in a new tab.

**Comment by AlexMountain** [comment]
Added this to the list in https://github.com/trevorskaggs/shelterly/issues/126
