### ISSUE TITLE
Deployment Strategy

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#141]
As we still will be working on the Launchpad over the next couple of months, I want to make sure we have a good first take on how our deployment script will function.  For the Trainings that will be put on in January, I want us to be working for a "production" environment.

This ticket will be a working space for us to track what is needed to complete this:

- [ ] Identify how we will handle new db/schema spin-up
- [ ] Identify how we will tie domain into new instance/schema.  Preferred format is: <organization>.shelterly.org/<incident-name>. Example: `nvadg.shelterly.org/bear-fire`. Can we make this format work to give the lambda function enough information to know where to reference? Are we going to need some kind of api wrapper to handle this parsing?
- [ ] Identify how we will load default users
- [ ] Identify how we will load default shelter objects

**Comment by rmeyers4** [comment]
1. In container, pull down latest code and run `npm run dev` to build js bundle.
2. In container, run `python ./manage.py collectstatic --clear`
2. Outside of container, clone repo into empty "build" directory, if not already done.
3. `docker cp shelterly:/home/shelterly/shelterly/static build/static` to copy generated static files into build directory
4. Copy `secrets.json` into `build/config`.
5. In build directory, run `docker build -t trevorskaggs/shelterly:prod .`
6. Push new image into repo: `docker push trevorskaggs/shelterly:prod`
7. Open AWS Console and navigate to Elastic Container Service: https://us-east-2.console.aws.amazon.com/ecs/home?region=us-east-2#/taskDefinitions/shelterly/status/ACTIVE
8. Select the checkbox corresponding to the latest revision and click "Create new revision". Leave all settings and click Create.
9. Navigate to https://us-east-2.console.aws.amazon.com/ecs/home?region=us-east-2#/clusters/shelterly/services/shelterly/update and select the new revision you created in the previous step. Check "Force new deployment" if you don't care about availability as the switchover is made. Update the service.
10. You can watch from this page as the new service is provisioned and the old one removed. https://us-east-2.console.aws.amazon.com/ecs/home?region=us-east-2#/clusters/shelterly/services/shelterly/tasks

**Comment by rmeyers4** [comment]
We can surely automate much of this, and use AWS Secrets Manager for the database credentials/hostname and django secret_key. A bit clunky but it works for now!

**Comment by trevorskaggs** [comment]
Hey, trying to run through this and not able to see any of the ECS content.  Might have made this in your account?
