### ISSUE TITLE
Add "Cross Street" field to SR

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#159]
To assist in locating the address while in the field and to prompt the Hotline folks to ask for the information, we are going to add and expose a "Cross Street" field on the SR object.

**Comment by AlexMountain** [comment]
Does this overlap with https://github.com/trevorskaggs/shelterly/issues/109?

**Comment by AlexMountain** [comment]
Going to close this as unnecessary.  Our updated address lookup supports cross streets and saves both street names in the address field.  Feel free to reopen if you still feel like we need an extra field for this.

**Comment by trevorskaggs** [comment]
This is just a text field to help people know roughly if they are in the right region.  This will really help if people are not able to get GPS directions on the fly (cell towers down in the field).  This isn't supposed to be for "the dog was at this cross street", but instead saying the "dog is at a house on this street, the nearest cross street is this".  This is a standard in FR type dispatching.

**Comment by trevorskaggs** [comment]
Actually, unless we find a very valid usecase, this could be captured in Directions.  This approach will reduce confusion for actual cross streets.
