### ISSUE TITLE
Additional Phone Number Regex Matches

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#160]
Had a couple of different approaches to Phone Number entry during the demo that were not currently supported by our Phone Number regex:
- [ ] XXX-XXX-XXXX
- [ ] (XXX) XXX-XXXX
- [ ] (XXX) XXX XXXX

**Comment by AlexMountain** [comment]
I feel like our old regex accepted these.  We should revert the regex and instead clean the phone submission on POST/PUT by removing everything that isn't a number, that way we can easily manipulate the raw number string for the display_phone.

**Comment by trevorskaggs** [comment]
Agreed, I actually played with this a bit last night and it messes up our display if we just change the actual accepting regex.   Better to do "parsing" on input, but still need something on the front end?

**Comment by AlexMountain** [comment]
Frontend should only need the regex update.  I believe the serializer should be used to clean out the extra chars/spaces.  Then our current display_phone field should just work.
