### ISSUE TITLE
Ability to Mass Copy a given Animal Object

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#162]
During Hotline Entry, we need the ability to quickly generate a variable number of duplicates of a given animal object.  The most common example of this is when someone calls in "30 chickens".  During hotline, they are not really going to be able to get a specific details for each chicken.  Instead, we are hoping the flow will look something like this:
- Add Animal
- Select Other, Fill out Description as "Chicken"
- Click button that prompts for how many copies we would like to generate

**Comment by AlexMountain** [comment]
I might want to brainstorm on the solution for this a bit.  What if instead of adding another workflow fork, we just added a field for taking in a "count", say, "No. of Animals", that did the above?

**Comment by trevorskaggs** [comment]
Yea, I was imagining a simple Modal, but a field would work just as easy.
