### ISSUE TITLE
Modify Time Displays to be 24-Hour Format

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#163]
For standardization purposes, customer would like all time entry and display to be in 24-hour format.

**Comment by SpencerjCarroll** [comment]
My thought is to implement a method field on the serializers, but open to thoughts if there is a better way.

Fields I found in a off-hand search.
- [ ] EvacAssignment: `start_time` `end_time`
- [ ] Animal: `last_seen`
- [ ] Service Request: `timestamp`
- [ ] PersonChange: `timestamp`

**Comment by AlexMountain** [comment]
I think we can control this with Moment on the frontend?  Might have to use a a full `.format()` definition instead of the convenient shorthand. See site for format examples: https://momentjs.com/

**Comment by AlexMountain** [comment]
Also realized our datetime picker will need to be adjusted for the input side of things, looks like a setting seen here: https://flatpickr.js.org/options/
