### ISSUE TITLE
Expose SR Timestamp

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#169]
To allow for adjustments to the timestamp of when an SR was generated, we are going to expose the field, but default the value to the current date/time on initial entry.

**Comment by AlexMountain** [comment]
I think I removed SR timestamp from the UI display in the few cases we had it.  Can you elaborate on it's importance/usage, and clarify if it just needs to show up on say the SR details, or if it needs to be in other SR references, like searches and DR views?

**Comment by trevorskaggs** [comment]
Seems like they are hoping that it is available when investigating priority and how they are doing on getting to all the work. This seems kind of like one of those things where, it has been important to know which ones were entered first as they get quite a bit behind.  Also a few people mentioned they would want to be able to adjust the entry time for cases where they took down the information while not near a computer... I'm not sure how solid that use case really is, but as time doesn't really give any priority currently, I think the risk is minimal.  I was just thinking about exposing it during SR Creation and Editing.

**Comment by AlexMountain** [comment]
So my takeaway here is add timestamp to the SR form and expose on SR details only.  This is simple enough to do, but for the sake of keeping things as simple as possible, I hope you don't mind if I inquire a little further.

Notably, I'm curious what usefulness the SR timestamp is actually providing here.  For example, say an SR is 7 days old, in that time, it could have had 0 DAs, or it could have had 7.  Wouldn't looking at the last dispatch VisitNote date or evaluating the a past due followup date actually provide what they're looking for here?  If the goal is to help provide information to figure out priority, I don't think the SR timestamp is it.  Plus burying this information in the SR details page makes it awkward to evaluate at scale.  If we think priority info is lacking in places, I feel like we could brainstorm on that and come up with something better.  Thoughts?

**Comment by AlexMountain** [comment]
Closing as obsolete.  We can reopen down the line if we are getting additional feedback that SR timestamps are in fact needed.
