### ISSUE TITLE
When doing Hotline animals are not saving for the Reporter/FR workflows.

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#172]
Seems to generate an SR and Reporter object, but the animals are not making it into the SR:

![image](https://user-images.githubusercontent.com/1276123/103257090-a3d23c00-4944-11eb-90a4-84acf56582c4.png)

On the backend it appears the animals are being generated and associated to the Reporter, but just seem to be missing the SR:
![image](https://user-images.githubusercontent.com/1276123/103257153-eb58c800-4944-11eb-8bc9-6af5f407641e.png)

**Comment by AlexMountain** [comment]
Since this was a easy fix and urgent I just made this change here:  https://github.com/trevorskaggs/shelterly/pull/173/commits/90881279ca6d6fc7812ad9db59df8154ed33e6c9
