### ISSUE TITLE
Update Django version in requirements.txt

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#198]
- To support JSON field, we need to make sure that we are requiring a version of Django that has JSON fields.

**Comment by SpencerjCarroll** [comment]
* Django JSON Field Support added in 3.1 (https://docs.djangoproject.com/en/3.1/releases/3.1/#jsonfield-for-all-supported-database-backends)
 * DRF JSON Field Support added in 3.12 (https://www.django-rest-framework.org/community/release-notes/#3120)
