### ISSUE TITLE
Add Reporter Searching to Animal Search

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#199]
Looks like we still need to add in searching Reporter by name on the Animal Search page!

**Comment by AlexMountain** [comment]
What does this mean?  What exactly didn't work or what are you looking for here?

When on the animal search page we already return results with owner first name, last name, address, and city.  Was there another field you wanted?

For reporter, it looks like we haven't added any search terms through the animal search.  Do you just want the same as the above?

**Comment by AlexMountain** [comment]
Sounds like we just want reporter first_name + last_name
