### ISSUE TITLE
Add feedback when saving a shelter with a duplicate name.

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#207]
Right now the page just bounces if you try to add a duplicate Building/Room/Shelter name.  We should remove this requirement from Building and Room models and add the error when POST/PUTing a dupe shelter name.

**Comment by AlexMountain** [comment]
I didn't even know we enforced unique names!  Are we worried about it causing any issues with generic shared names between sites for Rooms and Buildings?

**Comment by trevorskaggs** [comment]
Lets just make them not unique required.  Let's leave it on Shelter.
