### ISSUE TITLE
Track Where/When each time an Animals shelter location/room is changed

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#216]
As we are going to be using Shelters to support Internal and External (vet, foster, etc.) locations, we would like the ability to track the history of each time an animal is moved between not only shelters, but buildings/rooms.

**Comment by AlexMountain** [comment]
I believe we are capturing this information at this time on both the shelter/building/room object history and the animal history.  We need a comprehensive sweep on capturing action history in general so let's close this one off for now.
