### ISSUE TITLE
Develop Standard PDF Output of DA Evac Form

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#218]
To allow the Evac teams to get into the field with a paper version of the DAR, we need to design an easily printable and consistent format of output.   The form will look very similiar to the current DAR Form (Team Member Names, SR Details, Animals, Notes, Owner Contact, Etc.).  Main difference will be Status field will need to be Text in a line to allow for circling of correct status.

**Comment by trevorskaggs** [comment]
@parksjr To generate a mockup based on the current DAR page: dispatch/resolution/<pk>

**Comment by parksjr** [comment]
[DAR Form mock.pdf](https://github.com/trevorskaggs/shelterly/files/8191356/DAR.Form.mock.pdf)

Something like the attached mockup can be done using the jspdf library. Let me know if you want anything moved around or if I missed anything. @trevorskaggs

**Comment by trevorskaggs** [comment]
This is coming along nicely! 

Can we add this information the SR header section:
![image](https://user-images.githubusercontent.com/1276123/156933457-ff1e4264-fa95-45d4-b91d-0e6362fe878a.png)
 (and grab the Owner Phone Number also after the name)

Also are we able to add the Owner Contact section please:
![image](https://user-images.githubusercontent.com/1276123/156933475-a499f20f-d4f9-4890-bc08-80a6cea1da3d.png)
For the Dropdown Owner Contacted, let just make a list as checkboxes!

**Comment by parksjr** [comment]
@trevorskaggs thanks! I think the SR i created to test and mock around i didnt put an owner in, so I guess that pdf is what it would look like if there is no owner, if at all likely or possible. Anyway, i am attaching a new mock that includes the owner info. The page will likely always need a two page print out even with the minimum amount of info, so if you want me to try and cram things a little more I can, but not much room is there to begin with. Also a quick question: This pdf can be coupled to the ui elements and the data that is present on the UI, or do you envision having a separate endpoint to retrieve all of this data specifically for this pdf form on a click event? we can discuss next meet.

[DAR Form w owner.pdf](https://github.com/trevorskaggs/shelterly/files/8193855/DAR.Form.w.owner.pdf)

**Comment by trevorskaggs** [comment]
@parksjr Awesome! This is looking soooo good! Dont worry about multiple pages, this going to be standard if there are more than a few animals anyways.  As for your question, I dont really have a preference.  Right now the Animal Care Schedule is a single Django (non-rest) end point that is generating the raw HTML.  If you know a "best practice" way of doing this, I'm all ears!  @AlexMountain might have some insight into how he would like the API endpoint to be formed.

**Comment by parksjr** [comment]
It would be fine either way. Maybe easier to test if we just use ui elements and data already present on the page, which means no extra call to the API needed. The only piece of data I added to the prototype is the owner phone number so we'd just have to bring that into the actual web form, either display it next to the owner like in the pdf or in a hidden field.
