### ISSUE TITLE
Show Animals on Reporter Details Page

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#227]
Seems like Animals ended up popping off the Reporter page.
![image](https://user-images.githubusercontent.com/1276123/107600959-2bfd5f80-6bda-11eb-9716-ec8cfbd16f86.png)
![image](https://user-images.githubusercontent.com/1276123/107600968-33bd0400-6bda-11eb-8137-6330769355fe.png)

**Comment by AlexMountain** [comment]
@trevorskaggs They didn't drop off as much as they were never added because animals don't really "belong" to a reporter.  We can add them though.
