### ISSUE TITLE
Add * to Phone field where required.

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#279]
![image](https://user-images.githubusercontent.com/1276123/114126233-e218b900-98ac-11eb-8227-870a7668d7a2.png)

**Comment by AlexMountain** [comment]
Where required?  Is there anywhere it isn't required?

**Comment by trevorskaggs** [comment]
I think the only place not currently required is Shelter?

**Comment by trevorskaggs** [comment]
Basically, just really need to add to the Person form I think.

**Comment by AlexMountain** [comment]
Oh good point.  Turns out I already handled this in https://github.com/trevorskaggs/shelterly/pull/272 then!
