### ISSUE TITLE
In Production, SRs do not show up by default unless "Pending Only" is deselected

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#284]
![image](https://user-images.githubusercontent.com/1276123/114958943-e8f97b80-9e18-11eb-8c48-5b095b4d065e.png)
![image](https://user-images.githubusercontent.com/1276123/114958985-ff9fd280-9e18-11eb-83b6-5efaa9cb84e3.png)

**Comment by AlexMountain** [comment]
@trevorskaggs Something is clearly wrong with the code deployed to prod.  Here's a sample of SR data returned on the map:

```"id":1,"full_address":"4239 Rancho Road, Chico, CA 95973","latest_evac":null,"animal_count":1,"injured":false,"owner_objects":[{"id":1,"full_address":"4239 Rancho Road, Chico, CA 95973","display_phone":"231231232","display_alt_phone":"","address":"4239 Rancho Road","apartment":"","city":"Chico","state":"CA","zip_code":"95973","latitude":"39.800880","longitude":"-121.892970","first_name":"Trevor","last_name":"Skaggs","phone":"231231232","alt_phone":"","comments":"","agency":"","drivers_license":"","email":""}],"reporter_object":null,"animals":[{"id":1,"found_location":"","aco_required":"unknown","front_image":"","side_image":"","extra_images":[],"owner_names":["Trevor Skaggs"],"address":"","apartment":"","city":"","state":"","zip_code":"","latitude":null,"longitude":null,"order":0,"species":"cat","sex":"","pcolor":"","scolor":"","color_notes":"","size":"","age":"","status":"REPORTED","fixed":"unknown","aggressive":"unknown","confined":"unknown","injured":"unknown","name":"","behavior_notes":"","last_seen":null,"request":1,"reporter":null,"room":null,"shelter":null,"owners":[1]}],"evacuation_assignments":[],"visit_notes":[],"reported_animals":1,"owner_contacts":[],"sheltered_in_place":0,"unable_to_locate":0,"aco_required":false,"address":"4239 Rancho Road","apartment":"","city":"Chico","state":"CA","zip_code":"95973","latitude":"39.800880","longitude":"-121.892970","status":"open","timestamp":"2021-04-15T13:28:45.686061-07:00","directions":"","verbal_permission":false,"key_provided":false,"accessible":false,"turn_around":false,"followup_date":null,"reporter":null,"owners":[1]}```

What's missing here is the field `pending`, which is what that option keys off of.  Looking at the Deploy ticket code, the annotation and serializer for `pending` look fine, so I don't know why it's missing here.  Can you look at the code deployed to prod to see if it's actually there?  or attempt some kind of redploy?

**Comment by trevorskaggs** [comment]
Yea, I actually was just in there poking around and its seems like it might be missing a few master commits.  Going to work with Robbie today to get a new deployment container (and steps documented) up and going.  This is also likely the "Evac Team" issue as the cloud logs and database are showing that the DispatchTeam object/table don't exists!

**Comment by trevorskaggs** [comment]
I will take ownership of this ticket and close when I confirm changes work on prod.

**Comment by trevorskaggs** [comment]
Closing as OBE, was stale image.
