### ISSUE TITLE
Images do not work on Animal Card

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#297]
![image](https://user-images.githubusercontent.com/1276123/115814186-6b4de680-a3a9-11eb-9809-e397589d70ae.png)
![image](https://user-images.githubusercontent.com/1276123/115814228-815ba700-a3a9-11eb-87c2-eae75d86c6d8.png)

**Comment by AlexMountain** [comment]
Fixed here: https://github.com/trevorskaggs/shelterly/pull/290/commits/2c60ad760b5ad01f6cecd00289bc27d1962b8783 + here: https://github.com/trevorskaggs/shelterly/pull/290/commits/bceeec22c7457c10f763a73c03a7d8eb09874a49
