### ISSUE TITLE
Animal Search Page Query Timesout

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#305]
In production, the Animal Search page seems to be pretty inefficient and times out when there are 150+ animals in the system.

Example: https://sdhtest.shelterly.org/animals/search and querying all animals, not just owned or stray

**Comment by AlexMountain** [comment]
This is probably my fault.  I added the shelter object return to animals which was probably the cause.  I have ~150 animals in my local system and after updating the shelter serializer my local animal search times went from ~3 seconds to ~1 second and I assumed prod would be fine!  Oops...

@rmeyers4 Could I bug you to take a look at this one sometime soon and maybe throw the fix in https://github.com/trevorskaggs/shelterly/pull/290?

**Comment by rmeyers4** [comment]
@AlexMountain : I have some unpushed changes that address this and drop the total # of queries to 9.
