### ISSUE TITLE
Update Cat Colors

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#314]
Per guidance from John P, we are looking to have the following cat primary/secondary colors added:
Red, Cream, Blue
![image](https://user-images.githubusercontent.com/1276123/116302292-d9056400-a755-11eb-8da0-814eb3ca8c8e.png)

**Comment by AlexMountain** [comment]
@trevorskaggs What about smoke, fawn, and lilac (as seen in the picture but not in our list or mentioned above)?

**Comment by trevorskaggs** [comment]
Lets get em all if it doesnt cost much.  I thought grey kind of matched some of those colors, but 🤷
