### ISSUE TITLE
When adding "Clone Animals", the Animal Count in the Stepper does not reflect true value

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#327]
In the below I have added a 2x Dog, but the Stepper only reflects 1 animal added.
![image](https://user-images.githubusercontent.com/1276123/119213541-ae68ab80-ba74-11eb-9253-16eb8aa1ba35.png)

**Comment by AlexMountain** [comment]
Fixed here: https://github.com/trevorskaggs/shelterly/commit/715944af59bf7adf6992fe8141bcc7d1f1e7eb5e
