### ISSUE TITLE
DAR "Not Completed Yet" not skipping "Reported" animals

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#336]
When attempting to save a DAR with a SR of "Not Completed Yet" status, the form does not skip animals with a status of "Reported" and will not let you save.
![image](https://user-images.githubusercontent.com/1276123/129796191-2df811fe-ecd8-4233-a132-905d5c24a8ba.png)

**Comment by AlexMountain** [comment]
Fixed in here: https://github.com/trevorskaggs/shelterly/commit/275d9b9df2441703708d6443a2ab667a8effe981
