### ISSUE TITLE
Add "Horse" size to "Horse" species.

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#338]
Need to add the size of "Horse" for the "Horse" species.  This will be between "Pony" and "Draft"

**Comment by AlexMountain** [comment]
@trevorskaggs We used to have this but "Horse" isn't really a size and it create a one off problem all over the app where we try to display both species and size as it comes out to be a "Horse (Horse)".  We also removed size as a required field - could the users just not select a size if a horse is "horse" sized?

**Comment by trevorskaggs** [comment]
Let's go with "Standard"

**Comment by AlexMountain** [comment]
Done here: https://github.com/trevorskaggs/shelterly/commit/a97bf5be1ecbdeaa9c9de767f3d64a1ab2def2b3
