### ISSUE TITLE
Animal Image Doesn't Appear on SR Details

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#341]
After adding an Image to a given Animal, it doesn't appear to be displaying on the SR Details Animal Card.

![image](https://user-images.githubusercontent.com/1276123/129797144-52c7625d-d5f0-4334-b2a4-163a342ffe95.png)
![image](https://user-images.githubusercontent.com/1276123/129797165-be8d2fc2-c4da-4406-93d1-58d3264a19c2.png)

**Comment by AlexMountain** [comment]
@trevorskaggs Still waiting on you

**Comment by trevorskaggs** [comment]
This is not reproducible locally:
![image](https://user-images.githubusercontent.com/1276123/153528481-5418ebc7-e665-451a-ab72-0844323586b4.png)

I will verify again after I do a fresh push of master to the cloud.

**Comment by AlexMountain** [comment]
I stumbled upon this bug and fixed it here: https://github.com/trevorskaggs/shelterly/pull/374/commits/1e211877cc18231b8691e5b44f87035d839b89e8#diff-a36a576375c71f23fcd0aa699f2f4d0beaee4eabad8a9f1844d6c32f403e7fd5R19

Should be in master.  @trevorskaggs Please double check and close this one out if fixed.

**Comment by trevorskaggs** [comment]
Close as fixed!

**Comment by trevorskaggs** [comment]
![Uploading image.png…]()
