### ISSUE TITLE
Error when attempting to save an animal that already has an image, it removes the image!

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#343]
To recreate:
- Add an picture to an animal
- Edit animal and click save
- Animal Image seems to be removed!

Starting:
![image](https://user-images.githubusercontent.com/1276123/130173569-498bf82e-4304-49b1-83ee-dbfab0345826.png)
After no-change save:
![image](https://user-images.githubusercontent.com/1276123/130173585-7c2069a8-1bce-429a-b85f-a710a43a62af.png)
![image](https://user-images.githubusercontent.com/1276123/130173592-94441469-7e35-4f0e-a875-128b4eda289f.png)

**Comment by trevorskaggs** [comment]
I was able to reproduce this one on master locally. Steps:

1. Upload a picture (in my instance Front) to the animal.
2. Edit animal, the thumbnail is present in the file section, click save.
3. The animal no longer has a Front image
4. Upon reentering Edit Animal, the image in indeed missing!

**Comment by AlexMountain** [comment]
@trevorskaggs Just tested again and it works just fine for me. I have the following settings for my local:

```
DEBUG = True
USE_S3 = False
```

Have you confirmed this is an issue in the cloud?  I think we'll need to get on a call to further explore this one.
