### ISSUE TITLE
Change "Reset Password" to "Forgot Password" on Login Page

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#347]
Seems like we are consistently having folks "get confused that their password is not reset".  They are putting in their email and clicking the first "Reset Password", and then waiting for an email (they dont see the popup).  We will leave the button the same on the actual popup.
![image](https://user-images.githubusercontent.com/1276123/131585933-2e0055e6-c436-4d65-92d8-5e48845500a7.png)

**Comment by AlexMountain** [comment]
Changed here: https://github.com/trevorskaggs/shelterly/commit/1256d9751bb5604c605fdb3c30b9f3772e3bf18b
