### ISSUE TITLE
Error when click "back" from adding new animal to an owner

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#349]
Owner Page, Click [+] on Animals Section:
![image](https://user-images.githubusercontent.com/1276123/131728423-82d401c3-073f-45d2-8d03-c0fa4de3fa68.png)

Add Animal Page, click "<-" Back Button:
![image](https://user-images.githubusercontent.com/1276123/131728477-dc83d2e1-d415-4707-aa46-afc72417f610.png)

Error:
![image](https://user-images.githubusercontent.com/1276123/131728339-6a91630a-76ad-4ac5-bf72-ed04c115a175.png)

**Comment by AlexMountain** [comment]
Good catch, fixed here: https://github.com/trevorskaggs/shelterly/commit/28bd0f5e4619b318bbe083bcd5605cc90a834d4c
