### ISSUE TITLE
Image is lost after editing and animal

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#352]
If you add an image to an animal, then go back in and edit/save the animal the image is lost!

**Comment by AlexMountain** [comment]
@trevorskaggs I believe I am waiting on you to test this on your local master and in the cloud and provide reproduction steps.

**Comment by AlexMountain** [comment]
Also looks identical to https://github.com/trevorskaggs/shelterly/issues/343
