### ISSUE TITLE
Add Legend to Hotline Minimap

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#354]
For consistency we have been requested to add a mini-map to this page:
![image](https://user-images.githubusercontent.com/1276123/148412746-7f901de7-84be-4c35-8ee9-d8287c397d0f.png)

**Comment by AlexMountain** [comment]
@trevorskaggs Are you looking for an icon legend here...?  Sorry not clear on what we want.

**Comment by trevorskaggs** [comment]
Basically just something like 
![image](https://user-images.githubusercontent.com/1276123/153075812-a6f7d4b3-0020-4510-820f-80948d921253.png)
To show which icons mean what!
