### ISSUE TITLE
Animals cant stay in `Reported` when DAR is `Not Completed Yet`

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#355]
![image](https://user-images.githubusercontent.com/1276123/148413348-12f67582-1fb5-429a-8a9c-9e8ac3de618a.png)

**Comment by AlexMountain** [comment]
@trevorskaggs I cannot reproduce this one.  Can you retest on master for me?

**Comment by trevorskaggs** [comment]
This has been resolve on Master.
