### ISSUE TITLE
Deleted Animals still show up on Owner Page

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#361]
When deleting an animal, the card still shows up on the Owner Page.  When clicking into the Animal Detail page the api requests returns `{"detail":"Not found."}`.

![image](https://user-images.githubusercontent.com/1276123/151095040-04eff15f-aa9f-4309-82a8-a2bf492612cc.png)
![image](https://user-images.githubusercontent.com/1276123/151095059-41dc479d-404e-4abf-b4c4-2edee85cb09f.png)

**Comment by AlexMountain** [comment]
Should be fixed here: [2bac68a](https://github.com/trevorskaggs/shelterly/pull/364/commits/2bac68a5effb8afa4b5afd0cf2a0d560384bf03b)
