### ISSUE TITLE
Write python tests for existing functionality

### ISSUE THREAD

**Issue by rmeyers4** [trevorskaggs/shelterly#38]
We should write some tests for our existing python functionality. 
DRF has some nice built ins that extend Django's `RequestFactory`and `Client`.

**Comment by trevorskaggs** [comment]
@rmeyers4 You think we can get this one on lock for Sprint 1 (ending on July15)?

**Comment by rmeyers4** [comment]
@trevorskaggs : I think so, we don't have that many API endpoints exposed.
