### ISSUE TITLE
Add ability to attach photos to an Owner

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#391]
We will need to have the ability to attach photos to the Owner object.  Let's add a "Documents" section to the Owner Detail Page just below the Animal section: 
![image](https://user-images.githubusercontent.com/1276123/159961955-e95ddffc-59f8-4338-b6fa-a9d6010276c6.png)

- Add Document Section
- Add (+) icon to allow addition of additional photos/documents
- Add popup modal to allow uploading of photo.  Might be able to reuse some of the Animal picture logic?
- Add ability to remove documents, but need confirmation.

**Comment by AlexMountain** [comment]
@trevorskaggs Do we want this feature for Reporters too or just Owners?

**Comment by trevorskaggs** [comment]
Yea, lets apply to both if the lift isnt to high.

**Comment by trevorskaggs** [comment]
My favorite category of work: LESS!
