### ISSUE TITLE
DA Modifications

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#409]
Couple of requests from NVADG after reviewing DA form.

- Decrease Font Size
- Show Priority
- Add Page Numbers

**Comment by parksjr** [comment]
- [ ] show priority - where should we show the priority?
- [x] decreased font size
- [x] add page numbers

See the attached sample form (from my local environment) with the new font sizes and page numbers, let me know if any more change is needed there
[DAR-008 (11).pdf](https://github.com/trevorskaggs/shelterly/files/8722993/DAR-008.11.pdf)

**Comment by trevorskaggs** [comment]
Sorry, can we add Priority to the first Summary Page!

**Comment by parksjr** [comment]
I added the priority in place of the word "summary" next to the SR # for each summarized SR on the first page. Let me know if that needs changing. See attached sample from my local. I'll get a PR opened up right now.

[DAR-008 (15).pdf](https://github.com/trevorskaggs/shelterly/files/8747668/DAR-008.15.pdf)
