### ISSUE TITLE
Animal Model/Form Changes

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#41]
Notes from Live Demo:
- On Animal Form (add/edit), change the label Name > Animal Name 
- Add and expose an `Injured` NullableBoolean field to the Animal Model.  Unknown/Yes/No
- Remove Collared from Hotline Animal Form and Animal Model
- Remove Attended To from Hotline Animal Form and Animal Model

- Horse Choices
   - Sizes: Mini, Pony, Horse, Draft
   - Primary/Secondary Colors: Brown, Black, Bay, Chestnut, White, Grey
   - Ages: Young, Adult, Elderly

- Other Choices
   - Sizes: Small, Medium, Large
   - Ages: Young, Adult, Elderly

**Comment by AlexMountain** [comment]
Resolved in https://github.com/trevorskaggs/shelterly/pull/47
