### ISSUE TITLE
When a DA is "preplanned" give the option to "Default" a new team name based on the next available number.

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#413]
![image](https://user-images.githubusercontent.com/1276123/170343354-8813fafc-cae3-4e78-8e34-d1c614be273f.png)
Add a "default name" button that will save the Team Name as the next Team X.

**Comment by trevorskaggs** [comment]
Need to fix Team and Preplanned incriminators also!

**Comment by parksjr** [comment]
I've pushed what changes I have made to the front end, see PR #505

Latest change:

Added checkbox to the edit overlay box

![Screen Shot 2023-01-04 at 11 16 28 AM](https://user-images.githubusercontent.com/1508574/210601533-81183eda-c518-4aee-8b97-e887ac3ab80f.png)

If checked, it will post `{ defaultName: true }` to `{{baseUrl}}/evac/api/dispatchteam/{{teamId}}/` on Save

**Comment by parksjr** [comment]
Opened a [new PR](https://github.com/trevorskaggs/shelterly/pull/720) for this one, and closed the [old one](https://github.com/trevorskaggs/shelterly/pull/505)
