### ISSUE TITLE
Add Lat/Lon to DA Summary Document and DA Details Page

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#415]
Need to add the Lat/Lon for each SR on the DA Summary Printout.

**Comment by parksjr** [comment]
- For the DA printout, do we want the lat/lon to be displayed on either the summary for each SR, on the detailed pages per SR, or both?
- For the DA web page, i was thinking putting lat/lon directly under the address, right above the Owner for each SR, what do you think, @trevorskaggs @AlexMountain ?

**Comment by trevorskaggs** [comment]
Lets go with Both!  and Im good with that location!
