### ISSUE TITLE
Double Spinners

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#445]
When saving a new Evac Team Member, both buttons get spinners, not just the one you click! This seems to be in a few places where there are multiple action buttons.

**Comment by parksjr** [comment]
@trevorskaggs I found two areas this was happening (animal intake, and team member). If you know of more that I missed can you mention in here and I'll add it in. otherwise PR #450 is up.

**Comment by AlexMountain** [comment]
@parksjr Owner form during reporter/first responder intake

**Comment by parksjr** [comment]
thanks @AlexMountain I've updated the branch with the latest changes to include the owner form
