### ISSUE TITLE
Convert Animal Care Schedule to PDF

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#455]
Currently the Animal Care Schedule is a hacked together django url with a template rendering.  Lets convert this to our new PDF approach.  The current structure/fields are roughly correct.
[AnimalCareSchedule.pdf](https://github.com/trevorskaggs/shelterly/files/9122974/AnimalCareSchedule.pdf)

Nice to Haves:
- [ ] QR Code in upper right corner to Animal Details page

**Comment by parksjr** [comment]
Kennl No. comments:

logic:
Kennel No: <b>{% if animal.room %}{{ animal.room.building }} / {{ animal.room }}{% else %}N/A{% endif %}

rename Kennel No. to Location
