### ISSUE TITLE
New Building/Room Creation Redirection

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#476]
When add a building/room to a shelter, if it is the first building/room, once you click save the spinner goes and the building/room is created (on the backend), but the user stays on the creation page.  If you click "save" again, it will create an additional building/room, but still will not redirect.  This works if there is already an existing building.  Also you can recreate by removing all buildings for an existing shelter, then adding a brand new room.

**Comment by AlexMountain** [comment]
Fix pushed to master.
