### ISSUE TITLE
Create New Vet Models

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#500]
1. Vet Request
- PK
- Patient (Animal FK)
- Assignee (User FK, Nullable)
- Open (DateTime)
- Assigned (DateTime)
- Closed (DateTime)
- Presenting Complaints (new field, list of options to be provided by UCD) M2M
- Concern (Text Field)
- Priority (Urgent/When Available)
- Diagnosis (list of options to be provided by UCD, plus Other) (VET ONLY)

Treatment
- PK
- VetRequest (VetRequest FK)
- Start (DateTime, default to now, but allow for modification)
- End (DateTime)
- TreatmentCategory (TreatmentDescription FK - Category)
- TreatmentDescription (TreatmentDescription FK)
- Frequency (integer, every x hours, between 1-~)
- Quantity (float)
- Unit (ml/cap/tab)
- Route (IV/SQ/PO)

TreatmentRequest
- PK
- Assignee (User FK, nullable)
- Suggested Administration Time (DateTime)
- Actual Administration Time (DateTime)
- Treatment (Treatment FK)

TreatmentDescription
- PK
- Name
- Category

VR Search:
- Assignee
- Shelter
- Species
- Priority
- Open Date
- Color Triage

TP Search
- Assignee
- Shelter
- Species
- Start

**Comment by AlexMountain** [comment]
@trevorskaggs This ticket is ready for review and could use some thorough testing!
