### ISSUE TITLE
Modify Animal Care Schedule

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#516]
- [ ] Add Shelter Location
- [ ] Remove Owner Phone Number
- [ ] Make Date Time and AR# Columns Smaller

**Comment by parksjr** [comment]
This is up for review in #520

I was not 100% sure how to show the shelter location, so if a shelter object exists, I display the location info, including address, building and room name if available, and on a new line below the main image part. Let me know if that's what was desired.
