### ISSUE TITLE
When Requests are Cancelled, Make Sure Global Error Check for Unmounted

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#519]
On the Shelter Details page, if you move too quickly, it will cancel the request and throw an error.  The subsequent page will load, but the error pops up.

**Comment by AlexMountain** [comment]
Fixed here: https://github.com/trevorskaggs/shelterly/commit/8cbe08a4fa4bab7eb0f1d7ab4485608407e86c1d
