### ISSUE TITLE
Broken Links in SR Search

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#522]
When search for an SR, you can get a list of animals that include "Cancelled" ones.  If you click the link for their name you will get an animal details page that throws an error.
![image](https://user-images.githubusercontent.com/1276123/216667395-9cf8057e-dbbc-4932-a3be-f1d4f0cfe95b.png)
![image](https://user-images.githubusercontent.com/1276123/216667431-f68d792e-b385-4e92-9db6-caaffbc6ca04.png)
![image](https://user-images.githubusercontent.com/1276123/216667504-79f043bd-5050-419b-bc2a-62d6ba3d6f4b.png)

In other places we are removing these animals from the results!

**Comment by AlexMountain** [comment]
Fixed here: https://github.com/trevorskaggs/shelterly/commit/11560a3bd8f968d60596bcd59d3d7f1a091ab4a3
