### ISSUE TITLE
If only Reunited animals are in a given Open SR, the SR will show up on the Deploy Map

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#529]
![image](https://user-images.githubusercontent.com/1276123/217715810-6798ff2c-74c0-489d-852c-0cce8d6dbd2f.png)
![image](https://user-images.githubusercontent.com/1276123/217715794-a9ee2304-1285-4efb-95e8-5357774fa52e.png)

**Comment by AlexMountain** [comment]
@trevorskaggs Was this with fresh data? I was unable to reproduce; when I reunited an animal in an SR it became closed. If this is with fresh data can you provide any further info or reproduction steps?
