### ISSUE TITLE
Evac Team Members are Showing as Assigned When Not Actually Assigned

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#583]
![image](https://github.com/trevorskaggs/shelterly/assets/1276123/ebfd9774-c0e7-47a4-8c05-5123613ae537)
![image](https://github.com/trevorskaggs/shelterly/assets/1276123/10708474-71d6-462d-b8df-6a808b7451f2)

![image](https://github.com/trevorskaggs/shelterly/assets/1276123/3ae243cf-b493-4df5-abb8-8774ee236231)

**Comment by AlexMountain** [comment]
@trevorskaggs Attempted to fix this here: https://github.com/trevorskaggs/shelterly/commit/6d6e4b47c74235add0b75119fb1cb077580097c7

Please let me know if this persists on prod.
