### ISSUE TITLE
Page Numbers Not Printing if Content Encroaches on Margins on Owner/Liability Summary

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#603]

**Comment by parksjr** [comment]
Happen to have a screenshot? I have a bunch of owners on my instance with various levels of encroachment. I do have one case where the final page isn't counted and shows as `1 of undefined`, which I will fix now, but that doesn't sound like the same issue reported here.

**Comment by trevorskaggs** [comment]
Yup, that will likely fix most of the "edge" cases
