### ISSUE TITLE
Printed SR Updates

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#611]
SR Section: 
- [ ] Capitalize SIP for Animal Status
- [ ] Add Forced Entry
- [ ] Add Visit Notes

Animal Sections:
- [ ] Fixed
- [ ] Breed/Description
- [ ] Aggressive
- [ ] ACO Required
- [ ] Confined
- [ ] Injured
- [ ] Last Seen

**Comment by parksjr** [comment]
Added everything for this into the open PR #620 for the v0.6.9.6 milestone
