### ISSUE TITLE
In Printed SR Snake Case on all Status

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#622]
Reported that "Reported (Evac Requested)" was not output as Snake Case on the Printed SR, lets just double check all of them for that format.

**Comment by parksjr** [comment]
I assume this means proper noun capitalization, and not `snake_case`? I don't see any status displaying as snake_case anywhere, so I'll go with that.

**Comment by trevorskaggs** [comment]
Looks like this is kicking out ALL CAPS no the printed SR instead of Snake Case!
