### ISSUE TITLE
Decide on level of authentication security required

### ISSUE THREAD

**Issue by AlexMountain** [trevorskaggs/shelterly#63]
We need to come to a final decision on the level of security we feel we need for our app.  What we are currently using:

- Simple 4 number passwords for most users based on their telephone number. Unable to change without admin access.
- DRF tokens with knox enhancements (notably expiration), see https://github.com/James1345/django-rest-knox
- Regular cookie storage in the browser.

More secure options:
- Stronger passwords
- JWTokens instead of simple DRF tokens, see https://jwt.io/introduction/
- HttpOnly cookies, see https://latesthackingnews.com/2017/07/03/what-is-httponly-cookie/

All of these should be possible individually or together.  Some solid combination solutions may already be out there such as https://github.com/ssaavedra/drf-jwt-knox, although this one in particular may not be receiving updates.  We can circle on exact solutions once we determine the level of security we feel we need.

@trevorskaggs I am assigning this to you!

**Comment by AlexMountain** [comment]
I came across this library that seems worth considering:  https://github.com/aaronn/django-rest-framework-passwordless

Pros:
 - Removes weak and identifiable passwords.
 - Kind of an innate TFA due to requiring a user to check their email/phone
Cons:
 - Depending on workstations and how users are using Shelterly, it could be inconvenient for a user to check their email every time they login.

Open questions:
 - How does it work, what services does it use/support?
 - Are there costs associated with email or SMS?
 - Can we use our DRF knox tokens or would we have to change?

**Comment by trevorskaggs** [comment]
Alright my dudes, I think we might have a solution here!  As each incident is going to be its own environment, we run into the problem of progressively managing passwords.  As none of us want to be in the business of "enterprise support", I think the ultimate solution is going to looks something like this:

During initial loading of Users to new instance of Shelterly, assigned a random/complex password, but set to expired.  After a "Shelterly Launch", each user will receive an email and/or phone text with a "Magic Link", that will log them in automatically.  As they currently have an expired password, they will be required to set a new password.  This allows us to not have people end up with "bad passwords" or "misremembered passwords" during the initial phase of deployment.  We probably ultimately still want to expose a "reset password" functionality if someone does lose their password though! In those instance, I would imagine we could reuse a bit of the initial Launch logic, in that we could expire their current password and send them a new magic link.

Password Requirements: Min 8 Chars, 1 Upper, 1 Lower, 1 Number, 1 Character
Session Expiration: 1 Hour of Inactivity
Password Expiration: None

We also touched on a adding a "daily code", but we are going to stand down on this functionality for the time being.
