### ISSUE TITLE
Compress Photo Size (and format?) on Client Side

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#646]

**Comment by parksjr** [comment]
After a little bit of investigation on this, it appears that there is already a front-end, react library in place that compresses images before uploading them to the server. It's set to a maximum of 2mb for an image upload. I've tested this out with PNGs and JPGs alike, from my laptop Chrome browser, and it's working good.

Image compression library added from this PR: https://github.com/trevorskaggs/shelterly/pull/332

I have not tested with an iPad yet. I'd be curious to see if images are being uploaded larger than the 2mb's then that would suggest that there might be a bug on the iOS browser. Can we confirm that?

Regardless, my next steps are to do some testing on an iPad, see how that works, if I discover anything I will address.

**Comment by trevorskaggs** [comment]
The only catch here might be that we are using the built in "photo app" for uploading photos.  If you go to add a picture from the UI on a tablet it will bring up the photo app, and that is the image that you upload.
