### ISSUE TITLE
Canada addresses don't show up in Google results

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#658]
When setting an incident in Canada, I was not able to get Canadian addresses. The lat/lon seemed to be working as it was pushing me to WA for a BC address.

**Comment by AlexMountain** [comment]
@trevorskaggs Looked into this. It's easy to enable CA lookups but it will take a little bit of work to make them play nice. Probably 1-3 hours. Let me know what priority you want on this one.
