### ISSUE TITLE
Unable to add Permissions to Admin Accounts in New Organizations

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#659]
I'm only able to add Vet/User/etc. to my account for the initial Organization that was created in an instance.  If I update my user in a new org that I have been added to it will not throw an error, but the permission is not actually updated!

**Comment by AlexMountain** [comment]
Fuixed here: [6f7a999](https://github.com/trevorskaggs/shelterly/pull/656/commits/6f7a99947b8ad74b7d8e472ad81aad8dcce9b8ca)
