### ISSUE TITLE
Password Reset from User Admin Throws Error

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#662]
![image](https://github.com/trevorskaggs/shelterly/assets/1276123/aae517e1-790c-410b-bc1d-6598555261ff)

When trying to reset user password from user admin, it will bring up the "are you sure" prompt, but the api call yields the following error:

```  File "/home/sheltuser/shelterly/accounts/views.py", line 113, in perform_update
    ShelterlyUserOrg.objects.filter(user=user, organization=self.request.data.get('organizations')[0]).update(user_perms=self.request.data.get('user_perms', False), incident_perms=self.request.data.get('incident_perms', False), vet_perms=self.request.data.get('vet_perms', False), email_notification=self.request.data.get('email_notification', False))
TypeError: 'NoneType' object is not subscriptable```

**Comment by AlexMountain** [comment]
Fixed here: [6f7a999](https://github.com/trevorskaggs/shelterly/pull/656/commits/6f7a99947b8ad74b7d8e472ad81aad8dcce9b8ca)
