### ISSUE TITLE
Animal pictures

### ISSUE THREAD

**Issue by AlexMountain** [trevorskaggs/shelterly#68]
Currently we have omitted uploading images to animal objects in order to streamline things.  However, we need to identify and decide on the final requirements we want for these.  Questions:

- Can an animal have more than 1 image? infinite images?
- How do we envision the image upload process?
- Do we need to provide any other features such as cropping, resizing, etc?
- What pages do we display animals images on?
- What do the displayed images look like on the page(s)?  Slideshow inside a single image container? or display them all?  something else?

**Comment by trevorskaggs** [comment]
- We want to have at least 2 pictures: 1 front, 1 side.  Additional pictures should be allowed, but lets limit to 5 total per animal
- Lets have 2 big required [ + ] items at the top and a single [ + ] at the bottom. When a 3rd image is added, add another [ + ] until we hit the max limit
- No cropping, resizing
- Very minimum lets show at the top of Animal Detail page, in the upper right hand corner.
- When showing the pictures, let's do a slideshow in a single image container.  Start on "Front" picture and allowing scrolling.
