### ISSUE TITLE
Condense Action Menus ⚡ 

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#680]
Get rid of top layer and move information into the "Information" card.  Top line of the Card needs to be the ⚓ of the page now.  Add "Actions" menu right justified in that card.

Animal Detail
Service Request Detail
Owner Detail
Dispatch Assignment Detail
Vet Request Detail
Medical Record (Doesnt have actions, but needs top bar consoliation)

**Comment by AlexMountain** [comment]
@parksjr Let's start by keeping the Header/text at the top and only move the icons to an action button.

**Comment by parksjr** [comment]
What do we think about this? @trevorskaggs @AlexMountain 

![shelterly-actions-menu-o](https://github.com/trevorskaggs/shelterly/assets/1508574/2c494dc3-b4e8-4dd4-8567-0995d2077461)

**Comment by trevorskaggs** [comment]
Dropdown looks perfect dude! Only thing I see is I think we wanted to bump down to inside the card, basically justified right on the "Information" line.

**Comment by parksjr** [comment]
Oh that's not how I interpreted @AlexMountain's  comment. So we keep the header, and still move the actions menu down to the right of the information header?
