### ISSUE TITLE
Add Document Upload Support for Animal and Medical Record

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#688]

**Comment by parksjr** [comment]
@trevorskaggs 

Couple questions:

![Screenshot 2024-08-14 at 9 17 19 PM](https://github.com/user-attachments/assets/1adc0a04-2d72-43eb-9d3d-2d74ab194bf9)

- Do we want something like the screen above?
- Should the uploaded documents be shared with the upload-able documents on the Animal details page, or are they separate?
- the title says Animal AND Medical record, are there multiple places that need document upload support?

**Comment by trevorskaggs** [comment]
1. Let reuse what we have on the owner and SR page so far as it's the same functionality!
2. For the Animal page we want separate documents, as the images inside of the animal should be the actual animal!
3. Yup we want to add to the medical record object AND the animal object!
