### ISSUE TITLE
Update Image Storage Paths

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#693]
Currently it appears that Image AWS paths are a bit of an issue.
URL Example: https://{bucket-name}.s3.amazonaws.com/media/{instance}/None/images/image.jpg

 Main Issues:
1. Currently it looks like there is a `None` getting pipped into the url, originally I believe this was the Animal ID, but might need to expand to incorporate the incident also.
2. Currently if you upload 2 files with the same filname (`image.jpg`), they will overwrite eachother.  It appears that some tablets/phone do not use a dynamic filenaming convention when using the camera app.

**Comment by AlexMountain** [comment]
@trevorskaggs I am not sure where the `None` is coming from. The model is currently defined as such: `image = models.ImageField(upload_to='images/')`.

It sounds like we may need to customize the `upload_to` location to be `images/{incident}/{animal.id}/`
