### ISSUE TITLE
Page title says ‘React App’ instead of shelterly.org

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#709]
Description:
The title of the webpage shown in the browser tab says ‘React App’ instead 
of Shelterly.org (see screenshot). As a user, I should see a title relevant to 
the website I am on and not the name of the UI framework in use.

Steps:
1. Navigate to uat.shelterly.org and notice the title of the title of tab says 
‘React App’.

Expected Results:
The title of the website shown in the tab should say shelterly.org or possibly 
the organization in use and not the generic ‘React App’ title.
NOTE: ‘React App’ is consistently shown regardless if the user is logged into 
the app or not.

Actual Results:
The title of the website shown in the browser tab is ‘React App’

<img width="643" alt="image" src="https://github.com/trevorskaggs/shelterly/assets/1276123/9061f5f0-4c37-48a0-8c94-55b63ea2416b">

**Comment by AlexMountain** [comment]
Fixed here: https://github.com/trevorskaggs/shelterly/pull/738/commits/66077dfb261229e9d365049965752a335252ee4b
