### ISSUE TITLE
Pluralize Species in GeoJson Download

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#733]

**Comment by parksjr** [comment]
I tested this out on my local environment with the latest code from master and looks like the species are pluralized in the geojson description. Let me know if there is something else i should look for.

![Screenshot 2024-06-05 at 9 10 11 PM](https://github.com/trevorskaggs/shelterly/assets/1508574/4d43a823-eb41-4dad-9c4b-80ee72da7337)

**Comment by parksjr** [comment]
@trevorskaggs ☝️ no PR for this, just a comment for review
