### ISSUE TITLE
Expose Animal Notes on Intake from DA

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#761]
Customer is requesting the ability to see the Animal Notes field from the Intake from DA workflows. Suggesting using the small icon with a tooltip as a solution. Might also be worth exposing the Aggressive/ACO Required/Injured icons here if simple.

**Comment by parksjr** [comment]
Copied from the MR: 

adds animal notes, aggressive, aco, and injured properties to assigned animals

displays new property icons on shelter intake from DA form

## NOTE

**This new feature will only work for newly assigned animals, it is not retrofitted. Let me know if you want a separate effort to figure that in.**

## Screenshots

![Screenshot 2024-07-29 at 10 54 18 PM](https://github.com/user-attachments/assets/42f97252-548c-4315-ba44-1eab166036a2)

![Screenshot 2024-07-29 at 10 57 32 PM](https://github.com/user-attachments/assets/eb6d7bfb-f8e3-4eeb-944e-25590e99edef)

![Screenshot 2024-07-29 at 10 55 21 PM](https://github.com/user-attachments/assets/1cf67c63-48d5-4594-a96e-3e4083827dab)


Closes #761
