### ISSUE TITLE
S3 buckets for storing image data in production

### ISSUE THREAD

**Issue by AlexMountain** [trevorskaggs/shelterly#85]
Currently user uploaded images are stored locally to the Django server in the `media/images` folder.  This is fine for dev, but does it make more sense to store these in S3 buckets for prod?

**Comment by trevorskaggs** [comment]
Yes, i think this is correct.  We might need to develop a naming structure for buckets orgs/incidents. Maybe something like:
`s3://organization-name/incident-name/animals/animal-pk-UUID`
